services:
  pdm_db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${PDM_POSTGRES_DB}
      POSTGRES_USER: ${PDM_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PDM_POSTGRES_PASSWORD}
      PGPORT: ${PDM_POSTGRES_PORT}
    healthcheck:
      test: pg_isready -U ${PDM_POSTGRES_USER} -d ${PDM_POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  pdm:
    depends_on:
      pdm_db:
        condition: service_healthy
      gatekeeper:
        condition: service_healthy
    image: ghcr.io/agstack/openagri-pestanddiseasemanagement:latest
    command: /code/entrypoint.sh ${PDM_SERVICE_PORT}
    environment:
      POSTGRES_HOST: pdm_db
      POSTGRES_USER: ${PDM_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PDM_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PDM_POSTGRES_DB}
      POSTGRES_PORT: ${PDM_POSTGRES_PORT}
      ACCESS_TOKEN_EXPIRATION_TIME: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
      JWT_KEY: ${JWT_SIGNING_KEY}
      SERVICE_PORT: ${PDM_SERVICE_PORT}
      CORS_ORIGINS: ${CORS_ORIGINS}
      JWT_ALGORITHM: ${JWT_ALG}
      GATEKEEPER_BASE_URL: ${INTERNAL_GK_URL}
      USING_GATEKEEPER: ${PDM_USING_GATEKEEPER}
      GATEKEEPER_USERNAME: ${GATEKEEPER_SUPERUSER_USERNAME}
      GATEKEEPER_PASSWORD: ${GATEKEEPER_SUPERUSER_PASSWORD}
      SERVICE_NAME: ${SERVICE_NAME}
      LOGGING: ${LOGGING_LEVEL}
